name: Run query via SSH tunnel (hourly)

on:
  workflow_dispatch: {}          # запуск вручную из вкладки Actions
  schedule:
    - cron: "0 * * * *"          # каждый час по UTC

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest

    env:
      LOCAL_PORT: "6543"         # локальный порт для туннеля

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Configure SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -p "${{ secrets.SSH_PORT }}" "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts

      - name: Start SSH tunnel
        run: |
          ssh -fN \
            -p "${{ secrets.SSH_PORT }}" \
            -i ~/.ssh/id_ed25519 \
            -L "${LOCAL_PORT}:${{ secrets.DB_HOST }}:${{ secrets.DB_PORT }}" \
            "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}"
          # ждём, пока порт действительно поднимется
          for i in {1..20}; do
            (echo > /dev/tcp/127.0.0.1/${LOCAL_PORT}) >/dev/null 2>&1 && break
            sleep 0.5
          done
          echo "Tunnel ready on 127.0.0.1:${LOCAL_PORT}"

      - name: Run query and write CSV
        env:
          DB_URL: postgresql://${{ secrets.DB_USER }}:${{ secrets.DB_PASSWORD }}@127.0.0.1:${{ env.LOCAL_PORT }}/${{ secrets.DB_NAME }}
        run: |
          python run_query.py

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "ci@users.noreply.github.com"

      - name: Commit CSV if changed
        run: |
          if [ -n "$(git status --porcelain user_gold.csv)" ]; then
            git add user_gold.csv
            git commit -m "data: update user_gold.csv ($(date -u +'%Y-%m-%d %H:%M:%S') UTC)"
            git push origin HEAD:${GITHUB_REF_NAME}
          else
            echo "No changes to commit."
          fi
