name: Update CSV files hourly

on:
  schedule:
    - cron: "0 * * * *"   # каждый час (UTC)
  workflow_dispatch:

permissions:
  contents: write

# не даём задачам пересекаться (во избежание конфликтов туннелей/портов)
concurrency:
  group: update-csv
  cancel-in-progress: true

jobs:
  update:
    runs-on: ubuntu-latest
    env:
      USE_SSH: ${{ secrets.USE_SSH }}   # 'true' или 'false'

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install psycopg2-binary pandas
          fi

      # --- SSH-туннели (если USE_SSH == 'true') ---
      - name: Start SSH tunnels (if USE_SSH == true)
        if: ${{ env.USE_SSH == 'true' }}
        env:
          SSH_KEY:  ${{ secrets.SSH1_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SSH1_HOST }}
          SSH_PORT: ${{ secrets.SSH1_PORT }}
          SSH_USER: ${{ secrets.SSH1_USER }}
          DB1_HOST: ${{ secrets.DB1_HOST }}
          DB1_PORT: ${{ secrets.DB1_PORT }}
          DB2_HOST: ${{ secrets.DB2_HOST }}
          DB2_PORT: ${{ secrets.DB2_PORT }}
        run: |
          set -euo pipefail
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p "${SSH_PORT}" "${SSH_HOST}" >> ~/.ssh/known_hosts 2>/dev/null || true

          # Живые туннели + жёсткий фейл, если проброс не удался
          SSH_OPTS="-o ExitOnForwardFailure=yes -o ServerAliveInterval=30 -o ServerAliveCountMax=3 -o StrictHostKeyChecking=yes -i ~/.ssh/id_rsa -p ${SSH_PORT}"

          echo "→ Forward DB1 6543 -> ${DB1_HOST}:${DB1_PORT}"
          nohup ssh ${SSH_OPTS} -N -L 6543:${DB1_HOST}:${DB1_PORT} ${SSH_USER}@${SSH_HOST} > ssh_db1.log 2>&1 & echo $! > tunnel_db1.pid

          echo "→ Forward DB2 6544 -> ${DB2_HOST}:${DB2_PORT}"
          nohup ssh ${SSH_OPTS} -N -L 6544:${DB2_HOST}:${DB2_PORT} ${SSH_USER}@${SSH_HOST} > ssh_db2.log 2>&1 & echo $! > tunnel_db2.pid

          # ждём, пока порты реально поднимутся
          for i in {1..40}; do
            (echo > /dev/tcp/127.0.0.1/6543) >/dev/null 2>&1 && (echo > /dev/tcp/127.0.0.1/6544) >/dev/null 2>&1 && { echo "✓ Tunnels are up"; break; }
            sleep 0.5
          done

      - name: Run run_query.py
        env:
          DB1_USER:     ${{ secrets.DB1_USER }}
          DB1_PASSWORD: ${{ secrets.DB1_PASSWORD }}
          DB1_NAME:     ${{ secrets.DB1_NAME }}
          DB1_HOST:     ${{ secrets.DB1_HOST }}
          DB1_PORT:     ${{ secrets.DB1_PORT }}
          DB2_USER:     ${{ secrets.DB2_USER }}
          DB2_PASSWORD: ${{ secrets.DB2_PASSWORD }}
          DB2_NAME:     ${{ secrets.DB2_NAME }}
          DB2_HOST:     ${{ secrets.DB2_HOST }}
          DB2_PORT:     ${{ secrets.DB2_PORT }}
          USE_SSH:      ${{ env.USE_SSH }}
        run: |
          set -euo pipefail
          if [ "${USE_SSH}" = "true" ]; then
            export DB1_URL="postgresql://${DB1_USER}:${DB1_PASSWORD}@127.0.0.1:6543/${DB1_NAME}"
            export DB2_URL="postgresql://${DB2_USER}:${DB2_PASSWORD}@127.0.0.1:6544/${DB2_NAME}"
            echo "→ Using SSH tunnel URLs"
          else
            export DB1_URL="postgresql://${DB1_USER}:${DB1_PASSWORD}@${DB1_HOST}:${DB1_PORT}/${DB1_NAME}"
            export DB2_URL="postgresql://${DB2_USER}:${DB2_PASSWORD}@${DB2_HOST}:${DB2_PORT}/${DB2_NAME}"
            echo "→ Using direct DB URLs"
          fi

          python run_query.py   # сохранит user_gold.csv и user_total.csv

      - name: Commit & push if changed
        run: |
          git config user.name  "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add user_gold.csv user_total.csv || true
          git diff --cached --quiet || git commit -m "update csv files ($(date -u +'%Y-%m-%d %H:%M:%S') UTC)"
          git push

      # Показать логи SSH (на случай отладки), даже если шаги прошли
      - name: Debug SSH logs
        if: ${{ always() && env.USE_SSH == 'true' }}
        run: |
          for f in ssh_db1.log ssh_db2.log; do
            if [ -f "$f" ]; then
              echo "==== $f ===="
              tail -n +1 "$f" || true
            fi
          done

      # Аккуратно закрыть туннели
      - name: Stop tunnels
        if: ${{ env.USE_SSH == 'true' }}
        run: |
          set +e
          [ -f tunnel_db1.pid ] && kill $(cat tunnel_db1.pid) 2>/dev/null || true
          [ -f tunnel_db2.pid ] && kill $(cat tunnel_db2.pid) 2>/dev/null || true
